#!/usr/bin/env python3
"""Regenerate the Sefarim data file, one page per Sefer, and the sitemap.

Edit data/sefarim.json, then run:  python3 build.py
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).parent
SITE = "https://www.shalomjacobmemorial.com"
sefarim = json.loads((ROOT / "data/sefarim.json").read_text())

# 1. Data file used by index.html and he.html
(ROOT / "sefarim-data.js").write_text(
    "// Generated by build.py from data/sefarim.json — edit that file instead.\n"
    f"window.SEFARIM = {json.dumps(sefarim, ensure_ascii=False, indent=1)};\n"
)

# 2. One page per Sefer
HEAD = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title} · {en} · Shalom Jacob Memorial Institute</title>
  <meta name="description" content="{desc}">
  <link rel="canonical" href="{url}">
  <meta property="og:title" content="{title} — {en}">
  <meta property="og:description" content="{desc}">
  <meta property="og:image" content="{SITE}/images/{og}">
  <link rel="icon" href="../images/logo.jpg">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Frank+Ruhl+Libre:wght@400;500;700&family=Source+Sans+3:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="../styles.css">
  <script type="application/ld+json">{ld}</script>
</head>
<body>
<header class="site-header">
  <nav class="wrap nav" aria-label="Main">
    <a href="../index.html" class="brand"><img src="../images/logo.jpg" alt="The Shalom Jacob Memorial Institute"></a>
    <div style="display:flex;gap:10px;align-items:center">
      <a href="../index.html#publishing" class="btn btn-navy" style="background:transparent;color:var(--navy);border-color:var(--line)">All Sefarim</a>
      <a href="../index.html#support" class="btn btn-gold">Donate</a>
    </div>
  </nav>
</header>
<main>
"""

FOOT = """</main>
<footer>
  <div class="wrap foot-bottom">
    <span>© 2026 The Shalom Jacob Memorial Institute · Monsey, NY 10952</span>
    <a href="../index.html">Home</a>
  </div>
</footer>
</body>
</html>
"""


def e(s):
    return html.escape(s or "")


def link(s):
    return f'<a class="sefer-link" href="{s["id"]}.html"><span class="he">{e(s["title"])}</span><small>{e(s["en"])}</small></a>'


out = ROOT / "sefarim"
out.mkdir(exist_ok=True)
for i, s in enumerate(sefarim):
    url = f"{SITE}/sefarim/{s['id']}.html"
    desc = (f"{s['en']} ({s['title']}) by {s['author']} — {s['subject']}. "
            f"Republished in {s['republished']} by Rav Shalom Jacob זצ״ל with his annotations and commentary.")
    ld = json.dumps({
        "@context": "https://schema.org", "@type": "Book", "name": s["title"], "alternateName": s["en"],
        "author": {"@type": "Person", "name": s["author"]}, "inLanguage": "he", "about": s["subject"],
        "editor": {"@type": "Person", "name": "Rav Shalom Jacob"}, "url": url,
        **({"image": f"{SITE}/images/{s['cover']}"} if s.get("cover") else {}),
    }, ensure_ascii=False)
    cover = (f'<img src="../images/{s["cover"]}" alt="Cover of {e(s["en"])}" class="sefer-cover">' if s.get("cover")
             else f'<div class="sefer-cover sefer-cover-blank"><span class="he">ספר</span><b class="he">{e(s["title"])}</b></div>')
    first = f'<div><dt>First printed</dt><dd class="he">{e(s["first"])}</dd></div>' if s.get("first") else ""
    same = [o for o in sefarim if o["id"] != s["id"] and (o["author"] == s["author"] or o["title"] == s["title"])]
    related = (f'<h3 style="margin-top:2.4em">More from this author</h3><div class="sefer-links">{"".join(link(o) for o in same)}</div>'
               if same else "")
    prev, nxt = sefarim[i - 1] if i else None, sefarim[i + 1] if i + 1 < len(sefarim) else None
    pager = '<nav class="pager">' + (
        f'<a href="{prev["id"]}.html">← <span class="he">{e(prev["title"])}</span></a>' if prev else "<span></span>") + (
        f'<a href="{nxt["id"]}.html"><span class="he">{e(nxt["title"])}</span> →</a>' if nxt else "<span></span>") + "</nav>"

    body = f"""  <section class="sefer-page">
    <div class="wrap">
      <p class="crumbs"><a href="../index.html#publishing">Published Sefarim</a> / No. {s['id']}</p>
      <div class="sefer-grid">
        <div>{cover}</div>
        <div>
          <span class="eyebrow">Published by Rav Shalom Jacob <span class="he">זצ״ל</span></span>
          <h1 class="he sefer-title" lang="he">{e(s['title'])}</h1>
          <p class="sefer-en">{e(s['en'])}</p>
          <dl class="sefer-facts">
            <div><dt>Author</dt><dd class="he">{e(s['author'])}</dd></div>
            <div><dt>Subject</dt><dd class="he">{e(s['subject'])}</dd></div>
            {first}
            <div><dt>Republished</dt><dd class="he">{e(s['republished'])}</dd></div>
          </dl>
          <p>Rav Shalom <span class="he">זצ״ל</span> devoted himself to reviving the Torah of forgotten Rabbinic giants. Like each of the Sefarim he published, this edition was enriched with his own commentary and annotations and a biography of its author.</p>
          <div class="hero-cta" style="margin-top:1.4em">
            <a href="../index.html#support" class="btn btn-gold">Support the Publishing Project</a>
            <a href="../index.html#contact" class="btn btn-navy">Ask about this Sefer</a>
          </div>
          {related}
        </div>
      </div>
      {pager}
    </div>
  </section>
"""
    page = HEAD.format(title=e(s["title"]), en=e(s["en"]), desc=e(desc), url=url, SITE=SITE,
                       og=s.get("cover", "library-hero.jpg"), ld=ld) + body + FOOT
    (out / f"{s['id']}.html").write_text(page)

# 3. Sitemap
urls = [f"{SITE}/", f"{SITE}/he.html", f"{SITE}/privacy.html"] + [f"{SITE}/sefarim/{s['id']}.html" for s in sefarim]
(ROOT / "sitemap.xml").write_text(
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    + "".join(f"  <url><loc>{u}</loc></url>\n" for u in urls) + "</urlset>\n"
)
(ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n")
print(f"Built {len(sefarim)} Sefer pages, sefarim-data.js and sitemap.xml")
